### ISSUE TITLE
Is there any ability to filter films by User Rating? Not by Kinopoisk.

### ISSUE THREAD

**Issue by elxaz** [SuperZombi/HdRezkaApi#4]
Is there any ability to filter films by User Rating? Not by Kinopoisk.

**Comment by elxaz** [comment]
Add label "Question"

**Comment by SuperZombi** [comment]
This library doesn't have a search function.
Do you mean to add a rating attribute to the `rezka` object (parse the rating from the site)?

**Comment by elxaz** [comment]
no, I mean in general.
Maybe you can create some script for UI where user can sort films by user rating

**Comment by SuperZombi** [comment]
The library now contains a `rating` attribute
